services:
  mysql_db:
    image: mysql:8.0
    container_name: cotizaciones_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  legal_service_quotes:
    build:
      context: ./legal_service_quotes_microservice
    env_file:
      - .env
    environment:
      DATABASE_URL: "mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql_db:3306/${MYSQL_DATABASE}"
    depends_on:
      mysql_db:
        condition: service_healthy
    ports:
      - "8000:8000"

  ia_microservice:
    build:
      context: ./ia_microservice
    env_file:
      - .env
    depends_on:
      - legal_service_quotes
    ports:
      - "8001:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  db_data: